pipeline {
    agent {
        node {
            label 'jenkins-slave8.yvu.ch'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd Gadgeothek; ./gradlew build'
            }
            post {
                success {
                    archiveArtifacts '**/outputs/apk/*.apk'
                }
            }
        }
        stage('Analyze Code') {
            steps {
                sh 'cd Gadgeothek; ./gradlew lint'
            }
            post {
                success {
                    archiveArtifacts '**/reports/lint*.html'
                }
             }

        }
        stage('End2End Tests') {
            steps {
                sh '(cd Gadgeothek; ./gradlew connectedfullDebugAndroidTest)'
            }
        }
    }
}